Country=input("What country are your from? ")
print(f"You are from {Country}.")
Kids=input("Do you have kids? ")
print(f"You have kids.")
amount=input("How many kids do you have? ")
print(f"You have {amount} kid.")
Child=input("What is your child called?") 
print(f"The name of your child is {Child} ")
gender=input("Is your child a boy/girl? ")
print(f"Your child is a {gender}")
age=input("How old is he? ")
print(f"Your child is {age} years old.")
DOB=input("When was he born? ")
print(f"He was born on {DOB}.")
Size=input("What size are you? ")
print(f"You are a {Size}. ")
Parents=input("Who are your parents? ")
print(f"Your parents are {Parents}.")
liquid=input("What did you drink today? ")
print(f"You did drink {liquid}")
food=input("What are you having for dinner? ")
print(f"Tonight you will have {food}")
